l_polish:
 PRODUCTION_PRODUCTION_LABEL:0 "Produkcja"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "Magazyny"
 PRODUCTION_EFFICIENCY_LABEL:0 "§TWydajność§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "Wyposażenie"
 PRODUCTION_ADJUSTERS_LABEL:0 "Modyfikatory"
 PRODUCTION_MATERIALS_LABEL:0 "Materiały"
 PRODUCTION_FACTORIES_LABEL:0 "Fabryki"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "Fabryki wojskowe"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "Stocznie"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "Fabryki cywilne"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "Dostępne fabryki wojskowe"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "Dostępne stocznie"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "Dostępne fabryki cywilne"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL:0 "§TWyposażenie sił lądowych i powietrznych§!"
 PRODUCTION_NAVAL_LABEL:0 "§TWyposażenie marynarki§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§TWznoszenie budynków§!"
 PRODUCTION_PRODUCING_DAILY:0 "$AMOUNT$/dziennie"
 PRODUCTION_PRODUCING_WEEKLY:0 "$AMOUNT$/tygodniowo"
 PRODUCTION_PRODUCING_MONTHLY:0 "$AMOUNT$/miesięcznie"
 PRODUCTION_PRODUCING_YEARLY:0 "$AMOUNT$/rocznie"
 PRODUCTION_PRODUCING_ETA_DATE:0 "Ukończenie partii produkcyjnej: $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "Ukończenie napraw: $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "Za $AMOUNT$ dni"
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "Za $AMOUNT$ tyg."
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "Za $AMOUNT$ mies."
 PRODUCTION_PRODUCING_ETA_YEARS:0 "Za $AMOUNT$ lat(a)"
 PRODUCTION_PRODUCING_NEVER:0 "§RNigdy§!"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§GKliknij, by §Hzwiększyć priorytet§!.\nShift+klik, by nadać tej linii montażowej §Hnajwyższy priorytet§!.§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§GKliknij, by §Hzmniejszyć priorytet§!.\nShift+klik, by nadać tej linii montażowej §Hnajniższy priorytet§!.§!"
 PRODUCTION_PRIORITY_DELAYED:0 "Linia montażowa, która ma wysoki priorytet, otrzyma surowce szybciej niż linie o niskim priorytecie."
 PRODUCTION_EFFICIENCY:0 "£prod_eff  §TWydajność produkcji: $AMOUNT|H1%$§!"
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §TWydajność produkcji: $AMOUNT|Y1%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN:0 "£prod_eff  §TWydajność produkcji: $AMOUNT|H1%$§! ($GAIN|H3%$ tygodniowo)"
 PRODUCTION_EFFICIENCY_DESC:0 "§TŚrednia wydajność produkcji.\nWydajność wzrasta o $VALUE|H=2$% za każdą wyprodukowaną jednostkę (dzielone przez liczbę działających fabryk).§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§TBrak surowców: $AMOUNT|R1%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§TPrzydziel wyposażenie, by rozpocząć produkcję.§!"
 PRODUCTION_MATERIALS_OIL:0 "Ropa"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "Aluminium"
 PRODUCTION_MATERIALS_RUBBER:0 "Guma"
 PRODUCTION_MATERIALS_CHROMIUM:0 "Chrom"
 PRODUCTION_MATERIALS_STEEL:0 "Stal"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "Wolfram"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON:0 "Zbuduj pojazdy pancerne"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "§RNie wynaleziono§! pojazdów pancernych!"
 PRODUCTION_INFANTRY_BUTTON:0 "Zbuduj wyposażenie piechoty i artylerię"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "§RNie wynaleziono§! wyposażenia piechoty i artylerii!"
 PRODUCTION_AIRCRAFT_BUTTON:0 "Zbuduj samoloty"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "§RNie wynaleziono§! samolotów!"
 PRODUCTION_SHIPS_BUTTON:0 "Zbuduj okręty"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "§RNie wynaleziono§! okrętów!"
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 PRODUCTION_CONSUMER_GOODS:0 "Dobra konsumpcyjne"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§HDobra konsumpcyjne§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "Przy obecnej polityce gospodarczej obywatele oczekują, że $PERCENTAGE|H0%$ fabryk będzie produkowało dobra konsumpcyjne. Tylko fabryki cywilne mogą prowadzić taką produkcję. $TRADE_USABLE|H$ z $OPERATIONAL|H$ pozostałych zakładów można wykorzystać do celów handlowych."
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "Fabryki cywilne i wojskowe: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "Wymagana liczba fabryk dóbr konsumpcyjnych: $KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§TWymagania tej linii montażowej: $MATERIAL|H$ ($AMOUNT|0H$ jedn.).§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:0 "§TPotrzeba jeszcze $AMOUNT|0H$ szt., żeby osiągnąć pełną wydajność.§!\nProdukcja będzie kontynuowana ze §Rzmniejszoną prędkością§!."
 PRODUCTION_LINE_CANCEL:0 "§GKliknij, by §Hzamknąć§G tę linię montażową.§!"
 PRODUCTION_CREATE_VARIANT:0 "§HStwórz wariant§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§TAnuluj budowę.§!"
 PRODUCTION_VARIANT_OBSOLETE_YES:0 "Ponowny przydział"
 PRODUCTION_VARIANT_OBSOLETE_NO:0 "Demobilizacja"
 PRODUCTION_VARIANT_OBSOLETE_DESC:0 "§GKliknij§!, by zmienić.§!"
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "Zamknij linię montażową"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "Na pewno chcesz §Rzamknąć§! tę linię montażową?"
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "Anuluj budowę"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "Na pewno chcesz §Ranulować§! budowę: $CONSTRUCTION|H$ ($REGION|H$)?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "Anuluj projekty budowlane"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "Na pewno chcesz §Ranulować§! wszystkie projekty budowlane?"
 INFINITY:0 "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED:0 "Zapotrz.: $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "Wystaw w porcie: $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:0 "Wystaw jako element floty: $FLEET|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "Wybrana flota ($FLEET|H$) nie ma bazy."
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:0 "Wystaw wybraną flotę ($FLEET|H$) w bazie: $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "Ulokuj bazę: $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "Nie wybrano celu wystawienia."
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "Nie można wystawić."
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "Automatycznie"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "Złomowanie"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "Brak dostępnych baz. Jednostka zostanie zezłomowana po ukończeniu budowy."
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "Magazynowanie"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§GKliknij PPM, by przejść do prowincji.§!"
 WEEKLY_PRODUCTION:0 "Tygodniowa produkcja"
 PRODUCTION_WORKING_FACTORIES:0 "Liczba fabryk pracujących na jednej z twoich linii montażowych."
 PRODUCTION_CIVILIAN_FACTORIES_TOTAL:0 "Łączna liczba fabryk cywilnych: $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "Wykorzystane: $VALUE|Y$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "Podstawowy limit: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap  Limit wydajności produkcji: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "£prod_eff_cap  Limit wydajność produkcji wyznacza maksymalną £prod_eff  wydajność produkcji. Można go zwiększyć poprzez odpowiednie £tech_mod technologie."
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§HZużycie surowców przez każdą działającą fabrykę:§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "Linia nie marnuje tego surowca."
 PRODUCTION_MATERIAL_WASTE:0 "Linia marnuje $WASTE|R2$ jedn. tego surowca."
 PRODUCTION_SPEED:0 "Szybkość produkcji: $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§YModyfikatory wielkości produkcji:§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "Moc przerobowa: $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "Modyfikatory mocy przerobowej:"
 INDUSTRIAL_PROGRESS:0 "Prace nad budynkiem: $BUILDING|H$ - $PROGRESS|0H$/$COST|0H$ ( $VALUE|0%H$ )."
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "Podstawowa moc przerobowa: $VALUE|H$"
 INDUSTRIAL_BASE_SPEED:0 "Moc przerobowa fabryk ($FACTORIES|0H$): $VALUE|H$"
 PROD_COST_VALUE:0 "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE:0 "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "Posiadane: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "Eksport: $VAL|H$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:0 "Zapotrz.: $VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:0 "Zapotrz.: §Gpokryte§!"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "Dzienny bilans: $VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "Przy obecnym dziennym bilansie §Ypokryjemy§! zapotrzebowanie w ciągu $VALUE|0Y$ dni."
 PRODUCTION_EQUIPMENT_FILLED:0 "Zapotrzebowanie jest §Gpokryte§!."
 PRODUCTION_EQUIPMENT_LOSSES:0 "Wczoraj straciliśmy $VALUE|R$ wyposażenia."
 PROD_LINE_PLANE_DEST:0 "§Y(przeniesiono do rezerw)§!"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "Usuń poziom budynku"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "Na pewno chcesz §Rusunąć§! poziom tego budynku?"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "Anuluj budowę"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "Na pewno chcesz §Ranulować§! tę budowę?"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "Anuluj przekształcenie"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "Na pewno chcesz §Ranulować§! to przekształcenie?"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "Rozpocznij przekształcenie"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "Na pewno chcesz §Rprzekształcić§! ten budynek?"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "Codzienny przyrost: $VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "Brak surowców: $VAL|%+$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "Moc przerobowa naszych £factory_item $FACTORIES|Y$ fabryk wojskowych wynosi £production_cost $OUTPUT|Y$.\n$ITEM|Y$ kosztuje £production_cost $ITEM_COST|2Y$, co oznacza, że dziennie możemy wytworzyć $PERTIMEPERIOD$ szt.\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "Moc przerobowa naszych £naval_factory_icon $FACTORIES|Y$ stoczni wynosi £navprod_cost $OUTPUT|Y$.\n$ITEM|Y$ kosztuje £navprod_cost $ITEM_COST|2Y$, co oznacza, że dziennie możemy wytworzyć $PERTIMEPERIOD$ szt.\n"
 PRODUCTION_FACTORY_ASSIGN_DESC:0 "Kliknij, by przydzielić £factory_item fabryki wojskowe ($FACTORIES|Y$) do tej linii montażowej. Zapewni to dzienną moc przerobową na poziomie £production_cost $OUTPUT|Y$."
 PRODUCTION_DOCKYARD_ASSIGN_DESC:0 "Kliknij, by przydzielić £naval_factory_icon stocznie ($FACTORIES|Y$ ) do tej linii montażowej. Zapewni to dzienną moc przerobową na poziomie £navprod_cost $OUTPUT|Y$."
 PRODUCTION_BASE_OUTPUT:0 "Podstawowa moc przerobowa: $VALUE|Y$ x$MUL$"
 PRODUCTION_EFF_GAIN_HINT:0 "§YModyfikatory tempa wzrostu wydajności:§!"
 PRODUCTION_PRODUCING_NONE:0 "§RBrak§!"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 "Możliwość budowy: $VALUE|Y$"
 PROD_LINE_PLANE_DEST_RESERVES:0 "Samoloty z tej linii są obecnie przenoszone do rezerw."
 PROD_LINE_PLANE_DEST_UPGRADING:0 "Samoloty z tej linii są obecnie wykorzystywane do ulepszeń."
 PROD_LINE_PLANE_DEST_REINFORCEMENT:0 "Samoloty z tej linii są obecnie używane do modernizacji."
 PROD_LINE_LAND_DEST_RESERVES:0 "Wyposażenie z tej linii jest obecnie magazynowane."
 PROD_LINE_LAND_DEST_REINFORCEMENT:0 "Wyposażenie z tej linii jest obecnie używane do uzupełnień."
 PRODUCTION_UNITS_PER_DAY:0 "$UNITS|Y$ jedn. dziennie"
 PRODUCTION_UNITS_PER_WEEK:0 "$UNITS|Y$ jedn. tygodniowo"
 PRODUCTION_UNITS_PER_MONTH:0 "$UNITS|Y$ jedn. miesięcznie"
 PRODUCTION_UNITS_PER_YEAR:0 "$UNITS|Y$ jedn. rocznie"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "Ustaw domyślny skład skrzydeł tego lotniskowca"
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "Samoloty / kubatura lotniskowca."
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§YKubatura tego lotniskowca nie będzie w pełni wykorzystana.§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§RKubatura tego lotniskowca zostanie przekroczona, a stacjonujące na nim skrzydła otrzymają karę.§!"
 CARRIER_AIR_WING_INCREASE:0 "Zwiększenie liczby\n§GCtrl+LPM, żeby zwiększyć o§! §H5§!\n§GShift+LPM, żeby zwiększyć o§! §H10§!"
 CARRIER_AIR_WING_DECREASE:0 "Zmniejszenie liczby\n§GCtrl+LPM, żeby zmniejszyć o§! §H5§!\n§GShift+LPM, żeby zmniejszyć o§! §H10§!"
 INDUSTRIAL_PROGRESS_REPAIR:0 "$BUILDING|H$ - postępy napraw: $PROGRESS|%0H$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:0 "Modernizacja: $VALUE|0Y$"
 PROD_LINE_LAND_DEST_UPGRADING:0 "Wyposażenie z tej linii jest obecnie używane do modernizacji."
 PRODUCTION_LINE_CHANGE:0 "§GKliknij, żeby §Hzmienić§! produkowane wyposażenie.\nZachowasz część wydajności, jeśli wybierzesz nowszą wersję tego samego sprzętu.\n§!§RStracisz całe postępy tej linii.§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "Wyposażenie piechoty i artylerii"
 PRODUCTION_ARMOR_FILTER:0 "Pojazdy pancerne"
 PRODUCTION_AIR_FILTER:0 "Samoloty"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "Okręty liniowe"
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "Okręty osłonowe"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "Inne okręty"
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "Używane fabryki wojskowe"
 PRODUCTION_FILTER_DOCKYARDS:0 "Używane stocznie"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§RNie można wystawić§!"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§GKliknij§!, żeby ponownie przydzielić tę wersję i uznać ją za aktualny sprzęt."
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§GKliknij§!, żeby odesłać tę wersję do demobilu i uznać ją za nieaktualny sprzęt."
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "Zmiana wyposażenia"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "Na pewno chcesz §Rzmienić§! wyposażenie? Sprawi to, że stracisz $DAYS|R$ dni produkcji."
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "Niewystarczające zasoby ludzkie."
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "Zamknij wszystkie linie"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "Na pewno chcesz §Rzamknąć§! wszystkie linie produkcyjne?"
