l_braz_por:
 PRODUCTION_PRODUCTION_LABEL:0 "Produção"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "Armazenamento"
 PRODUCTION_EFFICIENCY_LABEL:0 "§TEficiência§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "Equipamento"
 PRODUCTION_ADJUSTERS_LABEL:0 "Ajustadores"
 PRODUCTION_MATERIALS_LABEL:0 "Materiais"
 PRODUCTION_FACTORIES_LABEL:0 "Fábricas"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "Fábricas militares"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "Estaleiros navais"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "Fábricas civis"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "Fábricas militares disponíveis"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "Estaleiros navais disponíveis"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "Fábricas civis disponíveis"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL:0 "§TEquipamento para exército e forças aéreas§!"
 PRODUCTION_NAVAL_LABEL:0 "§TEquipamento naval§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§TEdificações de construções§!"
 PRODUCTION_PRODUCING_DAILY:0 "$AMOUNT$/dia"
 PRODUCTION_PRODUCING_WEEKLY:0 "$AMOUNT$/semana"
 PRODUCTION_PRODUCING_MONTHLY:0 "$AMOUNT$/mês"
 PRODUCTION_PRODUCING_YEARLY:0 "$AMOUNT$/ano"
 PRODUCTION_PRODUCING_ETA_DATE:0 "Próxima conclusão: $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "Conclusão do reparo: $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "Em $AMOUNT$ dias"
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "Em $AMOUNT$ semanas"
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "Em $AMOUNT$ meses"
 PRODUCTION_PRODUCING_ETA_YEARS:0 "Em $AMOUNT$ anos"
 PRODUCTION_PRODUCING_NEVER:0 "§RNunca§!"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§GClique para §Haumentar a prioridade§!.\nUse Shift + clique para dar à produção a §Hmaior prioridade§!.§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§GClique para §Hdiminuir a prioridade§!.\nUse Shift + clique para dar à produção a §Hmenor prioridade§!.§!"
 PRODUCTION_PRIORITY_DELAYED:0 "Uma linha de produção com maior prioridade terá acesso aos recursos antes das linhas de produção com menor prioridade."
 PRODUCTION_EFFICIENCY:0 "£prod_eff §TEficiência de produção: $AMOUNT|H1%$§!"
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §TEficiência de produção: $AMOUNT|Y1%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN:0 "£prod_eff §TEficiência de produção: $AMOUNT|H1%$§! ($GAIN|H3%$ por semana)"
 PRODUCTION_EFFICIENCY_DESC:0 "§TEficiência média de produção de fábricas.\nA eficiência de produção aumenta por $VALUE|H=2$%/unidades produzidas, divididas igualmente entre as fábricas ativas.§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§TFalta de recursos: $AMOUNT|R1%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§TAtribua um equipamento para começar a produção.§!"
 PRODUCTION_MATERIALS_OIL:0 "Petróleo"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "Alumínio"
 PRODUCTION_MATERIALS_RUBBER:0 "Borracha"
 PRODUCTION_MATERIALS_CHROMIUM:0 "Cromo"
 PRODUCTION_MATERIALS_STEEL:0 "Aço"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "Tungstênio"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON:0 "Construir veículos blindados"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "Veículos blindados ainda §Rnão foram inventados§!!"
 PRODUCTION_INFANTRY_BUTTON:0 "Construir equipamentos de infantaria e artilharia"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "Equipamentos de infantaria e artilharia ainda §Rnão foram inventados§!!"
 PRODUCTION_AIRCRAFT_BUTTON:0 "Construir aeronaves"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "Aeronaves ainda §Rnão foram inventadas§!!"
 PRODUCTION_SHIPS_BUTTON:0 "Construir navios"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "Navios ainda §Rnão foram inventados§!!"
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 PRODUCTION_CONSUMER_GOODS:0 "Bens de consumo"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§HBens de consumo§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "Com nossas política econômica atual, as pessoas esperam que $PERCENTAGE|H0%$ do total de nossas fábricas produzam bens de consumo. Esta necessidade é atendida apenas por fábricas civis, deixando-nos com $OPERATIONAL|H$ fábricas onde $TRADE_USABLE|H$ podem ser usados para comercialização."
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "Fábricas civis e militares: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "Fábricas de bens de consumo necessárias: $KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§TEsta linha de produção usa $AMOUNT|0H$ unidades de $MATERIAL|H$.§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:0 "Mais §T$AMOUNT|0H$ unidades são necessárias para uma eficiência total.§!\nA produção continuará a uma §Rvelocidade reduzida§!."
 PRODUCTION_LINE_CANCEL:0 "§GClique para §Hcancelar§! esta linha de produção.§!"
 PRODUCTION_CREATE_VARIANT:0 "§HCriar variante§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§TCancelar esta construção.§!"
 PRODUCTION_VARIANT_OBSOLETE_YES:0 "Recomissionar"
 PRODUCTION_VARIANT_OBSOLETE_NO:0 "Descomissionar"
 PRODUCTION_VARIANT_OBSOLETE_DESC:0 "§GClique para alternar.§!"
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "Cancelar linha de produção"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "Tem certeza de que deseja §Rcancelar§! esta linha de produção?"
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "Cancelar edificação"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "Tem certeza de que deseja §Rcancelar§! a construção de $CONSTRUCTION|H$ em $REGION|H$?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "Cancelar edificações"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "Tem certeza de que deseja §Rcancelar§! todas as edificações?"
 INFINITY:0 "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED:0 "Requer: $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "Implantar no porto: $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:0 "Implantar na frota: $FLEET|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "O alvo de implantação $FLEET|H$ não tem uma base."
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:0 "Frota alvo de implantação $FLEET|H$ com base em $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "Base alvo de implantação em $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "Nenhum alvo para implantação definido."
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "Não é implantável"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "Automático"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "Descarte"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "Nenhuma base válida onde implantar. A unidade será descartada quando concluída."
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "Estocagem"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§GClique com o botão direito para ir à província§!"
 WEEKLY_PRODUCTION:0 "Produção semanal"
 PRODUCTION_WORKING_FACTORIES:0 "Esta é a quantidade de fábricas que estão atualmente trabalhando em uma de suas linhas de produção."
 PRODUCTION_CIVILIAN_FACTORIES_TOTAL:0 "Total de fábricas civis: $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "Em uso: $VALUE|Y$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "Capacidade da base: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap Capacidade de eficiência de produção: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "A £prod_eff_cap capacidade de eficiência de produção determina o valor máximo de sua £prod_eff  eficiência de produção. Pode ser aumentanda com £tech_mod tecnologias."
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§HRecursos por fábrica para produzir:§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "A linha não está desperdiçando este recurso."
 PRODUCTION_MATERIAL_WASTE:0 "A linha está desperdiçando $WASTE|R2$ deste recurso."
 PRODUCTION_SPEED:0 "Velocidade de produção: $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§YRendimento de produção modificado por:§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "Rendimento de fábricas: $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "Rendimento de fábricas modificado por:"
 INDUSTRIAL_PROGRESS:0 "$BUILDING|H$ está $PROGRESS|0H$/$COST|0H$ ( $VALUE|0%H$ ) concluído."
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "Rendimento de fábricas da base: $VALUE|H$"
 INDUSTRIAL_BASE_SPEED:0 "Rendimento de fábricas $FACTORIES|0H$: $VALUE|H$"
 PROD_COST_VALUE:0 "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE:0 "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "Adquirido: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "Das exportações: $VAL|H$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:0 "Total necessário: $VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:0 "Total necessário: §Gatendido§!"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "Saldo diário: $VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "Com nosso saldo diário atual, iremos §Yatender§! nossas necessidades em $VALUE|0Y$ dias."
 PRODUCTION_EQUIPMENT_FILLED:0 "Nossas necessidades estão §Gatendidas§! por agora."
 PRODUCTION_EQUIPMENT_LOSSES:0 "Perdemos $VALUE|R$ de equipamento ontem."
 PROD_LINE_PLANE_DEST:0 "§Y(Movido para as reservas)§!"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "Remover nível de construção"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "Tem certeza de que deseja §Rremover§! um nível desta construção?"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "Cancelar edificação"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "Tem certeza de que deseja §Rcancelar§! esta edificação?"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "Cancelar conversão"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "Tem certeza de que deseja §Rcancelar§! esta conversão?"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "Iniciar conversão"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "Tem certeza de que deseja §Rconverter§! esta construção?"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "Ganho diário base: $VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "Falta de recursos: $VAL|%+$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "Nossas £factory_item $FACTORIES|Y$ fábricas militares produzem £production_cost $OUTPUT|Y$.\n$ITEM|Y$ tem um custo de produção de £production_cost $ITEM_COST|2Y$, o que significa que podemos produzir $PERTIMEPERIOD$ por dia.\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "Nossos £naval_factory_icon $FACTORIES|Y$ estaleiros produzem £navprod_cost $OUTPUT|Y$.\n$ITEM|Y$ tem um custo de produção de £navprod_cost $ITEM_COST|2Y$, o que significa que podemos produzir $PERTIMEPERIOD$ por dia.\n"
 PRODUCTION_FACTORY_ASSIGN_DESC:0 "Clique para atribuir £factory_item $FACTORIES|Y$ fábricas militares a esta linha de produção. Isso concederia um rendimento total de £production_cost $OUTPUT|Y$ por dia."
 PRODUCTION_DOCKYARD_ASSIGN_DESC:0 "Clique para atribuir £naval_factory_icon $FACTORIES|Y$ fábricas militares a esta linha de produção. Isso concederia um rendimento total de £navprod_cost $OUTPUT|Y$ por dia."
 PRODUCTION_BASE_OUTPUT:0 "Rendimento base: $VALUE|Y$ x$MUL$"
 PRODUCTION_EFF_GAIN_HINT:0 "§YVelocidade de ganho de eficiência modificado por:§!"
 PRODUCTION_PRODUCING_NONE:0 "§RNenhuma§!"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 "Disponível para edificação: $VALUE|Y$"
 PROD_LINE_PLANE_DEST_RESERVES:0 "Os aviões desta linha estão atualmente sendo movidos para as Reservas"
 PROD_LINE_PLANE_DEST_UPGRADING:0 "Os aviões desta linha estão atualmente sendo usados para melhorias"
 PROD_LINE_PLANE_DEST_REINFORCEMENT:0 "Os aviões desta linha estão atualmente sendo usados para reforços"
 PROD_LINE_LAND_DEST_RESERVES:0 "Os equipamentos desta linha estão atualmente sendo estocados"
 PROD_LINE_LAND_DEST_REINFORCEMENT:0 "Os equipamentos desta linha estão atualmente sendo usados para reforços"
 PRODUCTION_UNITS_PER_DAY:0 "$UNITS|Y$ unidades por dia"
 PRODUCTION_UNITS_PER_WEEK:0 "$UNITS|Y$ unidades por semana"
 PRODUCTION_UNITS_PER_MONTH:0 "$UNITS|Y$ unidades por mês"
 PRODUCTION_UNITS_PER_YEAR:0 "$UNITS|Y$ unidades por ano"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "Definir composição padrão das unidades aéreas deste porta-aviões"
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "Capacidade de aviões/porta-aviões"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§YA capacidade deste porta-aviões não será usada totalmente§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§RA capacidade deste porta-aviões será excedida e as unidades aéreas estacionadas nele sofrerão uma penalidade§!"
 CARRIER_AIR_WING_INCREASE:0 "Aumentar quantidade\n§GUse Ctrl+clique para aumentar em§! §H5§!\n§GUse Shift+clique para aumentar em§! §H10§!"
 CARRIER_AIR_WING_DECREASE:0 "Diminuir quantidade\n§GUse Ctrl+clique para diminuir em§! §H5§!\n§GUse Shift+clique para diminuir em§! §H10§!"
 INDUSTRIAL_PROGRESS_REPAIR:0 "Progresso de reparo de $BUILDING|H$: $PROGRESS|%0H$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:0 "A melhoria requer: $VALUE|0Y$"
 PROD_LINE_LAND_DEST_UPGRADING:0 "Os equipamentos desta linha estão atualmente sendo usados para melhorias"
 PRODUCTION_LINE_CHANGE:0 "§GClique para §Hmudar§! o equipamento sendo produzido.\nVocê reterá parte da eficiência se trocar para uma versão mais recente do mesmo equipamento.\n§!§RVocê perderá todo o progresso desta linha.§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "Equipamento de infantaria e artilharia"
 PRODUCTION_ARMOR_FILTER:0 "Veículos blindados"
 PRODUCTION_AIR_FILTER:0 "Aeronave"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "Capitânias"
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "Navios de rastreamento"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "Outros navios"
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "Fábricas militares usadas"
 PRODUCTION_FILTER_DOCKYARDS:0 "Estaleiros navais usados"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§RNão foi possível implantar§!"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§GClique§! para recomissionar esta variante, marcando-a como equipamento atualizado."
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§GClique§! para descomissionar esta variante, marcando-a como equipamento desatualizado."
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "Trocar equipamento"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "Tem certeza que deseja §Rtrocar§! de equipamento? Isso fará você perder $DAYS|R$ dias de produção."
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "Mão de obra insuficiente"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "Cancelar todas as linhas"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "Tem certeza de que deseja §Rcancelar§! todas as linhas de produção?"
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME:0 "$STATE$ ($LVL|Y$)"
