l_simp_chinese:
 PRODUCTION_PRODUCTION_LABEL: "生产"
 PRODUCTION_EQUIPMENTPOOL_LABEL: "存量"
 PRODUCTION_EFFICIENCY_LABEL: "§T效率§!"
 PRODUCTION_EQUIPMENT_LABEL: "装备"
 PRODUCTION_ADJUSTERS_LABEL: "修正"
 PRODUCTION_MATERIALS_LABEL: "原料"
 PRODUCTION_FACTORIES_LABEL: "工业"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL: "军用工厂"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL: "海军船坞"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL: "民用工厂"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL_SHORT: "海军船坞"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL: "可用军用工厂"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL: "可用海军船坞"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL: "可用民用工厂"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE: "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL: "§T陆军和空军装备§!"
 PRODUCTION_NAVAL_LABEL: "§T海军装备§!"
 PRODUCTION_BUILDINGS_LABEL: "§T建筑施工§!"
 PRODUCTION_PRODUCING_DAILY: "$AMOUNT$/日"
 PRODUCTION_PRODUCING_WEEKLY: "$AMOUNT$/周"
 PRODUCTION_PRODUCING_MONTHLY: "$AMOUNT$/月"
 PRODUCTION_PRODUCING_YEARLY: "$AMOUNT$/年"
 PRODUCTION_PRODUCING_ETA_DATE: "下次完成日期：$DATE$"
 PRODUCTION_REPAIRING_ETA_DATE: "修复完成日期：$DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS: "$AMOUNT$日内"
 PRODUCTION_PRODUCING_ETA_WEEKS: "$AMOUNT$周内"
 PRODUCTION_PRODUCING_ETA_MONTHS: "$AMOUNT$月内"
 PRODUCTION_PRODUCING_ETA_YEARS: "$AMOUNT$年内"
 PRODUCTION_PRODUCING_NEVER: "§R无§!"
 PRODUCTION_REPAIRING_PAUSED_NAVAL_TRANSFER: "因为单位正在进行海运，维修已暂停"
 PRODUCTION_PRODUCING_NO_FACTORIES: "§R没有分配工厂§!"
 PRODUCTION_PRODUCING_NONE: "§R无§!"
 PRODUCTION_CAN_NOT_DEPLOY: "§R无法部署§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER: "人力资源不足"
 PRODUCTION_CAN_NOT_DEPLOY_NO_CAPITAL: "无法运抵补给首都"
 PRODUCTION_INCREASE_PRIORITY_LABEL: "§G点击§H增加优先级§!\nShift+点击使得生产获得§H最高优先级§!。§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL: "§G点击§H增加优先级§!\nShift+点击使得生产获得§H最低优先级§!。§!"
 PRODUCTION_PRIORITY_DELAYED: "相对于低优先级的生产线，资源会优先配置给拥有更高优先级的生产线。"
 PRODUCTION_EFFICIENCY: "£prod_eff §T生产效率：$AMOUNT|H2%$§!"
 PRODUCTION_EFFICIENCY_MOD: "£prod_eff §T生产效率：$AMOUNT|Y2%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN: "£prod_eff §T生产效率：$AMOUNT|H2%$§!（$GAIN|H3%$/日）"
 PRODUCTION_EFFICIENCY_DESC: "§T工厂平均生产效率。\n每生产一单位，生产效率增加$VALUE|H=2$%，平分在有效的工厂上。§!"
 PRODUCTION_RESOURCE_PENALTY: "§T缺少资源：$AMOUNT|R2%$§!"
 PRODUCTION_RESOURCE_PENALTY_WITH_MIO: "§T缺乏资源：$AMOUNT|R2%$§!（$FROM_MIO$）"
 PRODUCTION_ASSIGN_EQUIPMENT: "§T分配装备，开始生产。§!"
 PRODUCTION_MATERIALS_OIL: "石油"
 PRODUCTION_MATERIALS_ALUMINIUM: "铝"
 PRODUCTION_MATERIALS_RUBBER: "橡胶"
 PRODUCTION_MATERIALS_CHROMIUM: "铬"
 PRODUCTION_MATERIALS_STEEL: "钢"
 PRODUCTION_MATERIALS_TUNGSTEN: "钨"
 PRODUCTION_MATERIAL_VAL: "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON: "生产装甲车辆"
 PRODUCTION_VEHICLES_BUTTON_DISABLED: "装甲车辆§R还未研发§!！"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED: "我们§R没有军用工厂！§!"
 PRODUCTION_INFANTRY_BUTTON: "生产步兵与炮兵装备"
 PRODUCTION_INFANTRY_BUTTON_DISABLED: "步兵与炮兵装备§R还未研发§!！"
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED: "我们§R没有军用工厂！§!"
 PRODUCTION_AIRCRAFT_BUTTON: "生产飞行器"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED: "飞行器§R还未研发§!！"
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED: "我们§R没有军用工厂§!！"
 PRODUCTION_SHIPS_BUTTON: "建造舰队"
 PRODUCTION_SHIPS_BUTTON_DISABLED: "舰船§R还未研发§!！"
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED: "我们§R没有港口§!！"
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED: "我们§R没有海军船坞§!！"
 PRODUCTION_CONSUMER_GOODS_VALUE: "$VALUE$"
 PRODUCTION_CONSUMER_GOODS: "生活消费品"
 PRODUCTION_CONSUMER_GOODS_LABEL: "§H生活消费品§!"
 PRODUCTION_CONSUMER_GOODS_DESC: "在我们现行经济政策下，民众期望我们将总计$TOTAL_FACTORIES|H$座军用和民用工厂中的$PERCENTAGE|H0%$用于生产消费品。只有$GENERAL_FACTORIES|H$座民用工厂能满足这种需求，因此有$OPERATIONAL|H$座工厂剩余，其中$TRADE_USABLE|H$座可用于贸易。"
 PRODUCTION_CIV_AND_MIL_FACTORIES: "民用与军用工厂：$KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES: "必要生活消费品工厂：$KEY|H$"
 PRODUCTION_CONSUMER_GOODS_FACTORIES_BASE_EXPECTATION: "基础期望："
 PRODUCTION_CONSUMER_GOODS_FACTORIES_FACTOR: "系数："
 PRODUCTION_CONSUMER_GOODS_FACTORIES_FACTORS_MULTIPLIED: "系数相乘：$PERCENTAGE|H0%$"
 PRODUCTION_MATERIAL_COST_DESC: "§T这条生产线使用$AMOUNT|0H$单位$MATERIAL|H$。§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC: "§T还需要$AMOUNT|0H$单位资源才能达到最大效率。§!\n此生产线正因资源不足而§R减速§!。"
 PRODUCTION_LINE_CANCEL: "§G点击§!§R撤销§!这条生产线。\n§GShift+点击§!§R撤销§!所有生产线。"
 PRODUCTION_LINE_CANCEL_SHIP_REFIT: "§G点击§!§R废弃§!这艘正在改装的舰艇。"
 PRODUCTION_CREATE_VARIANT: "§H创建衍生型§!"
 PRODUCTION_CANCEL_CONSTRUCTION: "§T取消此次建设。§!"
 PRODUCTION_VARIANT_OBSOLETE_YES: "复役"
 PRODUCTION_VARIANT_OBSOLETE_NO: "退役"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC: "§G点击§!让此衍生型再次投入使用，把它标记为最新型装备。"
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC: "§G点击§!让此衍生型停止使用，把他标记为过时装备。"
 TRADE_FACTORIES_VALUE: "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE: "撤销生产线"
 CONFIRMCANCELPRODUCTIONLINE_DESC: "你确定要§R撤销§!这条生产线吗？"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE: "撤销所有生产线"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC: "你确定要§R撤销§!所有生产线吗？"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE: "切断设备"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC: "你确定要§R切断§!设备吗？这将使你失去$DAYS|R$日的产量。"
 CONFIRMCANCELCONSTRUCTION_TITLE: "取消建设"
 CONFIRMCANCELCONSTRUCTION_DESC: "你确定要§R取消§!在$REGION|H$的$CONSTRUCTION|H$建设吗？"
 CONFIRMCANCELCONSTRUCTION_RAILWAY_DESC: "你确定要§R放弃§!$NAME|H$铁路的建造行动吗"
 CONFIRMCANCELCONSTRUCTIONS_TITLE: "取消建设"
 CONFIRMCANCELCONSTRUCTIONS_DESC: "你确定要§R取消§!所有建设吗？"
 INFINITY: "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED: "需要：$AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE: "部署港口：$BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET: "部署特遣舰队：$FLEET|H$"
 PRODUCTION_DEPLOY_TO_RESERVE_FLEET_THEATER: "部署到战区预备舰队：$THEATER|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE: "部署目标舰队$FLEET|H$无基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET: "部署目标特遣舰队 $FLEET|H$到$STATE|H$的基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_THEATER: "部署目标战区$THEATER|H$的$STATE|H$基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_BASE: "在$STATE|H$部署目标基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE: "无部署目标。"
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE: "无法部署"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT: "自动"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING: "废弃"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC: "无有效基地可部署。单位在完成后将被废弃。"
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING: "储备"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM: "§G右击转入省份§!"
 PRODUCTION_NAVAL_DEPLOY_LIST: "部署目标"
 WEEKLY_PRODUCTION: "每周产量"
 PRODUCTION_WORKING_FACTORIES: "这是目前运作在生产线上的工厂数量。"
 PRODUCTION_WORKING_DOCKYARDS: "这是目前运作在生产线上的船坞数量。"
 PRODUCTION_WORKING_DOCKYARDS_FOR_REPAIRS: "这是目前正在从事军舰维修工作的船坞数量。"
 PRODICTION_MIC_TRANSFERED: "我们的$AMOUNT|Y$个工厂正在被$OVERLORD|Y$使用。"
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT: "$AMOUNT|Y$个军用工厂来自于我们的附属国。"
 PRODICTION_MIC_SENT_TO_OVERLORD: "我们的$AMOUNT|R$座军用工厂供宗主国使用，我们自己只剩下了$LEFT|H$座。"
 PRODICTION_MIC_RECEIVED_FROM_EXILE_DONATIONS: "$AMOUNT|Y$座我们的军用工厂是由流亡至我国的外国流亡政府所捐赠的。"
 PRODUCTION_MAX_EFFICIENCY_BASE: "基础上限：$VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT: "£prod_eff_cap 生产效率上限：$VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT: "£prod_eff_cap 生产效率上限决定了你 £prod_eff  生产效率的最大值。可以通过 £tech_mod 科技来提高上限。"
 PRODUCTION_RESOURCES_PER_FACTORY: "§H每个工厂消耗资源：§!"
 PRODUCTION_RESOURCE_COST: "$VALUE$"
 PRODUCTION_MATERIAL_NO_WASTE: "生产线没有浪费该资源。"
 PRODUCTION_MATERIAL_WASTE: "生产线正浪费$WASTE|R2$该资源。"
 PRODUCTION_SPEED: "生产速度：$SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS: "§Y产量修正：§!"
 INDUSTRIAL_CAPACITY_FACTOR: "工厂产量：$VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS: "工厂产量修正："
 INDUSTRIAL_PROGRESS: "$BUILDING|H$$PROGRESS|0H$/$COST|0H$（$VALUE|0%H$）完成。"
 INDUSTRIAL_PROGRESS_REPAIR: "$BUILDING|H$修复进程：$PROGRESS|%1H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT: "基础工厂产量：$VALUE|H$"
 INDUSTRIAL_BASE_SPEED: "$FACTORIES|0H$工厂产量：$VALUE|H$"
 PROD_COST_VALUE: "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE: "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_HEADER: "§H使用中的工厂§!"
 PRODUCTION_CIVILIAN_FACTORIES_TOTAL: "总数：$VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE: "未使用：$VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY: "正在使用中：$VALUE|R$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED: "拥有：$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_TRADE: "出口贸易：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_LICENSES: "出口生产许可：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS: "来自附属国：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS: "来自他国：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OCCUPATION: "来自占领：§G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER: "给宗主国：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS: "供给他国：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_TRADE: "进口贸易：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_LICENSES: "进口生产许可：$VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED: "损坏：$VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED: "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED: "$AMOUNT|0G$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE: "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE: "每日结余：$VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION: "依照现在的每日余额，我们将在$VALUE|0Y$日内§Y满足§!需求。"
 PRODUCTION_EQUIPMENT_FILLED: "现在我们的需求已§G满足§!。"
 PRODUCTION_EQUIPMENT_LOSSES: "我们昨天失去$VALUE|R$装备。"
 PROD_LINE_PLANE_DEST_RESERVES_DUE_TO_MANPOWER: "由于所需§Y增援§!的§H人力§!不足，动用了§Y后备队§!"
 PROD_LINE_PLANE_DEST_RESERVES: "增加§Y库存§!"
 PROD_LINE_PLANE_DEST_UPGRADING: "用于§Y升级§!"
 PROD_LINE_PLANE_DEST_REINFORCEMENT: "用于§Y增援§!"
 PROD_LINE_LAND_DEST_RESERVES: "正在§Y增加库存§!"
 PROD_LINE_LAND_DEST_UPGRADING: "用于§Y升级§!"
 PROD_LINE_LAND_DEST_REINFORCEMENT: "用于§Y增援§!"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE: "移除建筑"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC: "你确定要§R移除§!此建筑？"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE: "取消建设"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC: "你确定要§R取消§!此项建设？"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE: "取消转换"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC: "你确定要§R取消§!此次转换？"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE: "开始转换"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC: "你确定要§R转换§!该建筑？"
 PRODUCTION_EFFICIENCY_GAIN_BASE: "每日基础增长量：$VAL|H3%$"
 PRODUCTION_RESOURCE_FACTOR: "缺少资源：$VAL|%+$"
 PRODUCTION_RESOURCE_FACTOR_WITH_MIO: "缺乏资源：$VAL|%+$（$FROM_MIO$）"
 PRODUCTION_OUTPUT_EXPLAIN: "我们$FACTORIES|Y$座£factory_item 军用工厂的产量是$OUTPUT|Y$£production_cost 。\n$ITEM|Y$的生产花费是$ITEM_COST|2Y$£production_cost ，所以我们这条生产线的产量是$PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_REFIT: "我们$FACTORIES|Y$座£factory_item 军用工厂的产量是$OUTPUT|Y$£production_cost 。\n改装$FROM|Y$的花费是$COST|2Y$£production_cost ，所以我们能改装$PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL: "我们$FACTORIES|Y$座£naval_factory_icon 海军船坞的产量是$OUTPUT|Y$£navprod_cost 。\n$ITEM|Y$的生产花费是$ITEM_COST|2Y$£navprod_cost ，所以我们这条生产线的产量是$PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL_REFIT: "我们$FACTORIES|Y$座£naval_factory_icon 海军船坞的产量是$OUTPUT|Y$£navprod_cost 。\n改装$FROM|Y$的花费是$COST|2Y$£navprod_cost ，所以我们能改装$PERTIMEPERIOD$。\n"
 PRODUCTION_UNITS_PER_DAY: "$UNITS|Y$单位/日"
 PRODUCTION_UNITS_PER_WEEK: "$UNITS|Y$单位/周"
 PRODUCTION_UNITS_PER_MONTH: "$UNITS|Y$单位/月"
 PRODUCTION_UNITS_PER_YEAR: "$UNITS|Y$单位/年"
 PRODUCTION_FACTORY_ASSIGN_DESC: "点击分配£factory_item $FACTORIES|Y$座§Y军用工厂§!到该生产线。每座军用工厂的基础产量为£production_cost $OUTPUT|Y$/日。\n总产量会受到§Y资源§!、§Y生产效率§!和其他§Y生产修正§!的影响。"
 PRODUCTION_DOCKYARD_ASSIGN_DESC: "点击分配£naval_factory_icon $FACTORIES|Y$座§Y海军船坞§!到该生产线。每座海军船坞的基础产量为£navprod_cost $OUTPUT|Y$/日。\n总产量会受到§Y资源§!和其他§Y生产修正§!的影响。"
 PRODUCTION_BASE_OUTPUT: "基础产量：$VALUE|Y$ x $MUL|Y$"
 PRODUCTION_EFF_GAIN_HINT: "§Y效率增长速度修正：§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE: "设定该航母空军联队的默认编组"
 CARRIER_AIR_WING_LIMIT_UNDER: "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH: "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER: "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC: "飞机/航母载机容量"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER: "§Y该航母的载机容量没有完全利用§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER: "§R超过该航母载机容量。驻扎其中的空军部队将会遭受惩罚§!"
 CARRIER_AIR_WING_INCREASE: "增加空军部队数量\n§GCtrl+点击增加一半§!\n§GShift+点击增加到上限§!"
 CARRIER_AIR_WING_DECREASE: "减少空军部队数量\n§GCtrl+点击减少一半§!\n§GShift+点击全部移出§!"
 PRODUCTION_ENTRY_NEW: "（新型号）"
 PRODUCTION_ENTRY_OUTDATED: "（过时）"
 PRODUCTION_LINE_CHANGE: "§G点击§H改变§!生产的装备。\n如果你转而生产同一装备的新型号，将会保留一些生产效率。\n§!§R但你会失去该生产线当前的所有进度§!"
 PRODUCTION_LINE_CHANGE_NAVAL: "§G点击§H改变§!生产的装备。\n§!§R你将失去这条生产线上全部的进度。§!"
 PRODUCTION_EQUIPMENT_FILTER: "步兵和炮兵装备"
 PRODUCTION_ARMOR_FILTER: "装甲车辆"
 PRODUCTION_AIR_FILTER: "飞行器"
 PRODUCTION_CAPITAL_SHIPS_FILTER: "主力舰"
 PRODUCTION_SCREEN_SHIPS_FILTER: "屏卫舰"
 PRODUCTION_OTHER_SHIPS_FILTER: "其他舰种"
 PRODUCTION_LACKING_RESOURCES_FILTER: "资源充足"
 PRODUCTION_STOCKPILING_FILTER: "增加库存"
 PRODUCTION_REINFORCING_FILTER: "用于增援"
 PRODUCTION_UPGRADING_FILTER: "用于升级"
 PRODUCTION_OUTDATED_FILTER: "最新型号"
 PRODUCTION_REFITTING_FILTER: "改装"
 PRODUCTION_FILTER_CLICK_TO_HIDE: "§G点击§!§R隐藏§!此类别。"
 PRODUCTION_FILTER_CLICK_TO_SHOW: "§G点击§!§G显示§!此类别。"
 PRODUCTION_FILTER_SHIFTCLICK: "\n§GShift+点击§!§R隐藏§!所有其他类别。"
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN: "\n§GShift+点击§!重新§G显示§!所有其他类别。"
 PRODUCTION_FILTER_RIGHTCLICK: "\n§G右键点击§!展开/收起此类别。"
 PRODUCTION_FILTER_ARMS_FACTORIES: "军用工厂使用"
 PRODUCTION_FILTER_DOCKYARDS: "海军船坞使用"
 INTEL_CIVILIAN_FACTORIES_USED_ON_TRADE: "用于贸易的民用工厂数量估计"
 INTEL_ARMS_FACTORIES_USED_ON_EQUIPMENT: "用于军事装备的军用工厂数量估计"
 INTEL_ARMS_FACTORIES_USED_ON_ARMOR: "用于装甲载具的军用工厂数量估计"
 INTEL_ARMS_FACTORIES_USED_ON_AIR: "用于飞机的军用工厂数量估计"
 INTEL_DOCKYARDS_USED_ON_CAPITAL: "用于主力舰的海军船坞数量估计"
 INTEL_DOCKYARDS_USED_ON_SCREEN: "用于屏卫舰的海军船坞数量估计"
 INTEL_DOCKYARDS_USED_ON_OTHER: "用于其他舰船的海军船坞数量估计"
 PRODUCTION_DRAG_N_DROP: "§G拖拽§!改变§Y优先级§!。"
 PRODUCTION_COLLAPSE: "§G点击§!收起。\n§GCtrl+点击§!收起所有这些类别。\n§GShift+点击§!收起所有生产线。"
 PRODUCTION_EXPAND: "§G点击§!展开。\n§GCtrl+点击§!展开所有这些类别。\n§GShift+点击§!展开所有生产线。"
 PRODUCTION_FACTORY_SCALE_UP: "§G点击§!以§Y$SCALE$倍§!单位查看。"
 PRODUCTION_FACTORY_SCALE_DOWN: "§G点击§!恢复§Y1倍§!单位查看。"
 PRODUCTION_ADD_FACTORIES_CLICK: "§G点击§!§Y+1§!\n§GCtrl+点击§!§Y+5§!\n§GShift+点击§!§Y+10§!"
 PRODUCTION_SUB_FACTORIES_CLICK: "§G点击§!减去§Y1§!\n§GCtrl+点击§!减去§Y5§!\n§GShift+点击§!减去§Y10§!"
 PRODUCTION_ADD_1: "§G点击§!添加§Y+1§!"
 PRODUCTION_ADD_5: "§GCtrl+点击§!添加§Y+5§!"
 PRODUCTION_ADD_10: "§GShift+点击§!添加§Y+10§!"
 PRODUCTION_SUB_1: "§G点击§!减去§Y1§!"
 PRODUCTION_SUB_5: "§GCtrl+点击§!减去§Y5§!"
 PRODUCTION_SUB_10: "§GShift+点击§!减去§Y10§!"
 PRODUCTION_ADD_NAVAL_FACTORIES_CLICK: "§G点击§!添加§Y+1§!"
 PRODUCTION_SUB_NAVAL_FACTORIES_CLICK: "§G点击§!减去§Y1§!"
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT: "§G点击§!在队尾增加新的生产线。\n§GShift+点击§!在队首插入新的生产线。"
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME: "$STATE$（$LVL|Y$）"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK: "§R我们的储备目前没有装备可以改装为：$VARIANT|H$§!"
 PRODUCTION_LINE_CONVERT_HEADER: "从储备中改装"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION: "改装顺序："
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY: "$NUM|Y0$$VARIANT|G$（§H$TYPE$§!）花费： "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY_NO_TYPE: "$NUM|Y0$$VARIANT|G$花费： "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY: "$NUM|Y0$$VARIANT|G$（§H$TYPE$§!）"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY_NO_TYPE: "$NUM|Y0$$VARIANT|G$"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY: "§H$NUM$§!£resources_strip|$FRAME$ "
 PRODUCTION_LINE_CONVERT_DESC: "从储备中改装会将储备中的§H过时的装备§!或者§H缴获的装备§!改装成当前生产线所指定的型号。这会一直持续到储备耗尽。"
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL: "改装速度：§G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE: "基础值：$VAL|=+%0$"
 PRODUCTION_LINE_CONVERT_RES_NEED: "从$NAME|Y$进行改装需要以下战略资源："
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY: "\n   £resources_strip|$FRAME$：($NEW|Y0$-$OLD|G0$)=$SUM|R0$"
 PRODUCTION_LINE_SHIP_NAME_ALLOCATE: "此名称尚未分配给任何其他船只。§G点击§!添加按钮将此名称分配给此生产队列。"
 PRODUCTION_LINE_RAILWAY_GUN_NAME_ALLOCATE: "此名称尚未分配给任何其他列车炮。§G点击§!添加按钮将此名称分配给此生产队列。"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE: "许可装备生产速度：$VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL: "§H许可装备工厂产出§!\n总量：$VALUE|+%$\n详细："
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION: "§Y许可装备科技差§!：\n 基础值：$BASE|+%$\n 修正后合计：$TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER: "§Y生产许可修正§!：\n 基础值：$BASE|+%$\n 修正后合计：$TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION: "§Y与许可者不在同一阵营§!：$VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE: "§Y没有使用中的生产许可§!：$VALUE|+%$"
 LICENSED_EQUIPMENT_UPGRADE_XP_COST_MODIFIER: "许可装备：$VAL$"
 LICENSED_PURCHASE_CIC_COST: "§Y这个生产许可花费§!：£civ_factory $AMOUNT|Y$"
 PRODUCTION_NAVAL_REPAIRS_LABEL: "维修队列"
 PRODUCTION_NAVAL_NAME_LIST: "船舰名称"
 PRODUCTION_RAILWAY_GUN_NAME_LIST: "列车炮名称"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_FALLBACK: "船舰名称"
 PRODUCTION_RAILWAY_GUN_NAME_LIST_BUTTON_FALLBACK: "列车炮名称"
 PRODUCTION_NAVAL_NAME_LIST_EMPTY_NOT_ALLOWED: "§R不允许使用空白名称。§!"
 PRODUCTION_NAVAL_NAME_LIST_TOO_FEW_PRODUCED: "§R名称将超过生产队列中的舰船数量。§!"
 PRODUCTION_NAVAL_NAME_LIST_REMOVE: "§G点击§!§H移除名称§!"
 PRODUCTION_NAVAL_NAME_LIST_NAME_RESERVED: "$NAME|H$ 已经在使用中。"
 PRODUCTION_NAVAL_NAME_LIST_ADD_NAME: "§G点击§!命名$NAME|H$序列的下一艘$EQUIPMENT|H$。"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_NAME: "这一序列的下一艘 $EQUIPMENT|H$将被命名为$NAME|H$。"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_CLICK: "§G点击§!更改名称。"
 PRODUCTION_SHIP_REFIT_TOTAL_COSTS: "§H改装$COUNT|T$船总花费：§!\n"
 PRODUCTION_SHIP_REFIT_BASE_ICCOST: "船体：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_BUILD_ICCOST: "新模块：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_CONVERT_ICCOST: "转换模块：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_DISMANTLE_ICCOST: "拆除模块：$ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_QUICKEST_TIME: "如果分配给最大数量的§H船坞§!，这将需要$DAYS|H$日来完成。"
 PRODUCTION_SHIP_REFIT_TOOLTIP_DIFF_HEADER: "§H改装的效果§!"
 PRODUCTION_SHIP_REFIT_TOOLTIP_FROM_VARIANT_HEADER: "来自$VARIANT$（$SHIP_COUNT|H$被选中）"
 PRODUCTION_SHIP_REFIT_TOOLTIP_NO_STAT_CHANGES: "没有数据改变"
 PRODUCTION_SHIP_REFIT_TOOLTIP_MORE_VARIANTS: "和其他装备型号（$SHIP_COUNT|H$被选中）"
 PRODUCTION_TANK_REFIT_BASE_ICCOST: "底盘：$ICCOST|H2$"
 PRODUCTION_TANK_REFIT_QUICKEST_TIME: "§H生产效率§!最大时每个分配的工厂可改装$NUM_UNITS_PER_TIME_PERIOD$。"
 PRODUCTION_SUB_UNIT_FILTER: "仅显示 $SUBUNIT|H$（$COUNT|H$ 符合）"
 PRODUCTION_EQUIPMENT_ROLE_NO_FILTER: "显示所有任务"
 PRODUCTION_EQUIPMENT_ROLE_FILTER: "仅显示具有$ROLE|H$作用的装备"
 PRODUCTION_COST_MODIFIERS: "§Y£production_cost£生产花费修正：§!"
 PRODUCTION_COST_MODIFIER_ITEM: "$REASON$：$VALUE|-%$"
 BONUS_PRODUCTION_COST_FACTOR: "生产产出花费"
 BONUS_PRODUCTION_CAPACITY_FACTOR: "产量"
 BONUS_PRODUCTION_EFFICIENCY_CAP_FACTOR: "生产效率上限"
 BONUS_PRODUCTION_EFFICIENCY_GAIN_FACTOR: "生产效率增长"
 BONUS_PRODUCTION_RESOURCE_NEED_FACTOR: "生产资源需求"
 BONUS_PRODUCTION_RESOURCE_PENALTY_FACTOR: "生产资源惩罚"
 BONUS_PRODUCTION_CONVERSION_SPEED_FACTOR: "生产转换速度"
